predicted_prot_dir: "/media/tassnina/Study/VT/Research_Group/SARSCOV2/SARS-CoV-2-network-analysis/outputs/networks"
positive_protein_file: "/media/tassnina/Study/VT/Research_Group/SARSCOV2/SARS-CoV-2-network-analysis/fss_inputs/pos-neg/2020-03-sarscov2-human-ppi/pos.txt"

